version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "npx prisma migrate deploy && node server.js"
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
